CC = gcc
PROG = Othello_Deluxe
CFLAGS = -Wall -g


SDL_DIR=${HOME}/SDL2
SDLLIB_DIR=${SDL_DIR}/lib
SDLINC_DIR=${SDL_DIR}/include
LIBS=-L$(SDLLIB_DIR) -lSDL2 -lSDL2_ttf -lSDL2_image
INCLUDES=-I${SDLINC_DIR} 

OBJ_O=obj
SRC_S=src
BIN_B=bin
LIB_L=lib


clean: 
	rm -f ${PROG}
	rm -f *.o

javel:
	rm -i 



h:
	
	@echo 'Option existantes'
	@echo '- all'
	@echo '- test'
	@echo '- clean'
	@echo '- javel'

